import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
startup_mode = "Maximized"
